.travis.yml, requirements.txt, requirements_dev.txt, setup.py
Moved dependencies on packages into setup.py and added version pins in
requirements.txt files.
Also re-ordered the way travis installs:
First we install using requirements.txt (and thus get the desired
versions) then we install using `pip install -e .` which should not
install any new packages.
See:
https://packaging.python.org/discussions/install-requires-vs-requirements/
for current best practises regarding dependency handling.
=> Fixed requirements handling:

README.md, openapi_spec_validator/__main__.py, setup.py, tests/integration/test_main.py
Hi,
i've added a CLI interface for validating local files. For that i've created an `entry_point` in `setup.py` pointing to a new file `openapi_spec_validator/__main__.py`. After you installed the package with pip you are able to run
```bash
$ openapi_spec_validator path_to.yaml
```
to run a validation. This could also be extended to run tests on URLs, not just local files.
=> Added CLI interface for ad-hoc validation

.gitignore, .travis.yml, openapi_spec_validator/decorators.py, openapi_spec_validator/resources/schemas/v2.0/schema.json, openapi_spec_validator/validators.py, setup.py, tox.ini
minor syntax changes to support python2.7
=> python2.7 support

openapi_spec_validator/resources/schemas/v3.0.0/schema.json, tests/integration/test_validators.py
See [the Fixed Fields section of the specs](https://swagger.io/specification/#fixed-fields-51), towards the end:
> A parameter MUST contain either a schema property, or a content property, but not both.
Adding the `oneOf` constraint requiring either `content` or `schema` fixes this issue.
The same issue applies to all objects that refer to Parameter Objects as their basis, such as e.g. Header Objects. I will add to this branch until I've adjusted all of those, and notify when this is done.
=> OpenAPI 3.0.0 schema fix: Parameter Object must contain 'schema' or 'content'

openapi_spec_validator/validators.py, tests/integration/test_validators.py
see https://github.com/OAI/OpenAPI-Specification/issues/1608
=> disable required properties checks in allOf blocks

openapi_spec_validator/decorators.py, openapi_spec_validator/validators.py, tests/integration/test_shortcuts.py, tests/integration/test_validate.py, tests/integration/test_validators.py
=> Validation errors wrapper

openapi_spec_validator/validators.py, tests/integration/test_shortcuts.py, tests/integration/test_validate.py
Fixes #20 
- wrap jsonschema `ValidationError`s in `OpenAPIValidationError`, which inherits from `ValidationError`
This allows the user to expect a consistent error to be raised if the exception is invalid.
Note that with the use of `six.raise_from(...)` the original exception is preserved via exception chaining in python 3.
I think this is best practice, _but_ it may be annoying because each exception essentially prints twice.
test script, `try.py`:
```python
#!/usr/bin/env python
import yaml
from openapi_spec_validator import validate_spec
with open("openapi.yaml") as f:
y = yaml.load(f.read())
validate_spec(y)
```
python 3:
```
> python3 try.py
jsonschema.exceptions.ValidationError: 'somestring' is not of type 'integer'
Failed validating 'type' in schema:
{'default': 'somestring', …
```
=> wrap jsonschema exceptions with OpenAPIValidationError

openapi_spec_validator/__init__.py
To make building RPMs of package easier when using ascii by default.
=> Replace unicode character for RPM build.

requirements_dev.txt, setup.py
Flake8 runs both pyflakes and pycodestyle. Pep8 is deprecated and renamed to pycodestyle.
=> Switch test requirement to pytest-flake8.

setup.py
Should make the page at https://pypi.org/project/openapi-spec-validator/ render as Markdown. See: https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata
=> Signal PyPI to format the long_description as Markdown

README.md, setup.py
Don't require a beta version of PyYAML to solve a security issue we're not exposed to.
See discussion in #60 
I'll add a security note in the README too.
=> revert pyyaml requirement version

openapi_spec_validator/__main__.py, setup.py
[pathlib](https://bitbucket.org/pitrou/pathlib)  isn't maintained anymore. So maybe pathlib2 is a better choice
Fixes #63
=> Replace pathlib with pathlib2

README.md, setup.py
PyYAML 5.1 was released a few days ago. Hopefully this alleviates the concerns that were raised with using the beta release (4.1b).
I've reverted the security note that was added as well, as it no longer applies.
Backwards *incompatible* changes are listed here : https://github.com/yaml/pyyaml/issues/265
=> bump PyYAML to 5.1 for CVE-2017-18342

openapi_spec_validator/generators.py, requirements.txt, setup.py
Avoid hard coding the validator functions in SpecValidatorsGeneratorFactory and just use the defaults in Draft4Validator.
This allows us to work with both > and < jsonschema 3.
I wasn't sure if we actually need the list of validators to be a subset of what is in Draft4Validator. If we don't we can simplify this a little.
=> Support jsonschema 3

openapi_spec_validator/__init__.py, openapi_spec_validator/__main__.py, openapi_spec_validator/handlers.py, tests/integration/test_main.py
Spec from standard input
Fixes #73
=> STDIN spec support

setup.py
The short description will show up when doing a `pip3 search openapi-spec-validator` and the short description is also used by external tools.
For example the gitlab license tools takes, in order, description then long description. In this case, the long description is the contents of README.md: eg: https://jlecomte.gitlab.io/-/projects/rd-webhooks/-/jobs/325696880/artifacts/gl-license-management-report.json
=> Add a short description to setup.py

.travis.yml
Adds Python 3.8 to the testing matrix
=> Add Python 3.8 to Travis matrix

openapi_spec_validator/handlers/base.py, openapi_spec_validator/handlers/file.py, openapi_spec_validator/handlers/requests.py, openapi_spec_validator/handlers/urllib.py
=> Handlers timeout setup fix

openapi_spec_validator/exceptions.py, openapi_spec_validator/validators.py, tests/integration/test_validators.py
=> Detect duplicate operationId fix

README.rst
Thank you for this validator!
I had a hard time understanding why my valid Swagger 2.0 was not validated, since the version number is explicit and this module states it can validate both. I had to go to the `__init.py__` file to discover that `validate_spec` is aliased to `validate_v3_spec`. I hope this documentation improvement saves some time for other users 🙂
Have a good day!
=> Document Python validation of Swagger v2 specs

openapi_spec_validator/validators.py, tests/integration/data/v3.0/parent-reference/openapi.yaml, tests/integration/data/v3.0/parent-reference/recursive.yaml, tests/integration/data/v3.0/parent-reference/recursive2.yaml, tests/integration/test_shortcuts.py
JSON schema references can be nested in complex schemas.
Recurse in dereferencing logic until the returned item is no
longer a reference.
Also: Added a recursion to test data and fixed a typo
in test_shortcuts.py.
=> Recurse references in validation

openapi_spec_validator/decorators.py, tests/integration/data/v3.0/petstore.yaml
This is not a "proper fix" as the proper fix should check if `$ref`
is used as a name of the property, but this works for the purposes of #123
fixes #123
=> A `$ref` may be a property name and in such cases it's not hashable

tests/integration/test_validate.py
I fixed just minor typos in the some test class names.
=> Fix test class name

openapi_spec_validator/__main__.py, tests/integration/data/v3.0/missing-description.yaml, tests/integration/test_main.py
I often miss the context provided by jsonschema library, so I'm trying to add it.
Given the following erroneous schema (it misses a `description`):
```yaml
---
openapi: 3.0.0
info:
title: test
description: test
version: 0.0.1
paths:
"/":
get:
description: Get the API root
responses:
200:
content:
application/json:
schema:
type: string
```
without this PR, openapi-spec-validator displays:
```
{'content': {'application/json': {'schema': {'type': 'string'}}}} is not valid under any of the given schemas
Failed validating 'oneOf' in schema['properties']['paths']['patternProperties']['^\\/']['patternProperties']['^(get|put|post|delete|options|head|patch|trace)$'
]['properties']['responses']['patternProperties']['^[1-5](?:\\d{2}|XX)$']:
{'oneOf': [{'$ref': '#/definitions/Response'},
{'$ref': …
```
=> On validation error: add cause and context.

.github/workflows/python-publish.yml, .github/workflows/python-test.yml, .travis.yml, openapi_spec_validator/generators.py, openapi_spec_validator/handlers/file.py, openapi_spec_validator/handlers/requests.py, openapi_spec_validator/handlers/urllib.py, openapi_spec_validator/handlers/utils.py, openapi_spec_validator/readers.py, openapi_spec_validator/schemas.py, openapi_spec_validator/shortcuts.py, openapi_spec_validator/validators.py, poetry.lock, pyproject.toml, tests/integration/conftest.py, tests/integration/test_main.py, tox.ini
Fixes #130
Fixes #135 
`jsonschema` released version 4.0.0 which dropped support for Python 2.7 and 3.5. `openapi-spec-validator` should do the same to support new versions of `jsonschema`. Both upstream dependencies and downstream dependents have already upgraded their `jsonschema` version constraints, which leads to conflicts with `openapi-spec-validator`.
=> Drop Python 2.7 and 3.5 support and bump dependency upper bounds

README.rst, openapi_spec_validator/__init__.py, openapi_spec_validator/__main__.py, openapi_spec_validator/factories.py, openapi_spec_validator/resources/schemas/v3.1/schema.json, openapi_spec_validator/validators.py, poetry.lock, pyproject.toml, tests/integration/conftest.py, tests/integration/data/v3.1/petstore.yaml, tests/integration/test_main.py, tests/integration/test_shortcuts.py, tests/integration/test_validate.py, tests/integration/test_validators.py
Rebased version of #128 after #137 was merged
=> Implements OpenAPI 3.1 spec validator 

openapi_spec_validator/validators.py, tests/integration/test_validators.py
I added some code to handle allof case with required set at the parent object level (a bit different than the case originally done in https://github.com/p1c2u/openapi-spec-validator/issues/97 ).
=> feat: handle allof when required linked to parent object (#97)

pyproject.toml
Fix error when using the openapi-spec-validator package while deploying Python Function App in Microsoft Azure.
Add version to setuptools in toml file.
Resolve this error:
`ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
setuptools from https://files.pythonhosted.org/packages/3b/02/8d4d27b1cacaac2d129a27d17a22d92a2a5eedcb7817d4ed8ab0d4daf5c4/setuptools-60.9.3-py3-none-any.whl#sha256=e4f30b9f84e5ab3decf945113119649fec09c1fc3507c6ebffec75646c56e62b (from openapi-spec-validator==0.4.0->-r requirements.txt (line 180))`
=> Update pyproject.toml - add version to setuptools 

openapi_spec_validator/schemas.py, poetry.lock, pyproject.toml
=> use importlib_resources instead of pkg_resources

openapi_spec_validator/factories.py, poetry.lock
* removed redundant factory subclassing
* update openapi-schema-validator dependency (subclassing fixes)
Fixes #162
=> jsonschema subclassing fix

pyproject.toml, tests/integration/test_shortcuts.py, tests/integration/validation/test_validators.py
=> tests mark network

openapi_spec_validator/validation/validators.py, tests/integration/data/v2.0/missing-reference.yaml, tests/integration/validation/test_validators.py
=> Responses schema validation

pyproject.toml
PyYAML is no longer runtime dependency (7bca8cd and 7cbc3f6).
`openapi-spec-validator` requires `jsonschema-spec` that in turn wants `PyYAML = ">=5.1"`.
Fixes: https://github.com/p1c2u/openapi-spec-validator/issues/179
=> Drop no longer used runtime dependency on PyYAML

tests/integration/validation/test_exceptions.py
Short strings can be interned as an optimization in the Python interpreter, so comparing them by identity (`is`, memory address) can succeed in practice, but it is neither correct nor reliable when comparing by equality (`==`, value) is intended.
Fixes a warning (that could become a test failure depending on interpreter implementation details):
```
tests/integration/validation/test_exceptions.py:468
/builddir/build/BUILD/openapi-spec-validator-0.5.2/tests/integration/validation/test_exceptions.py:468: SyntaxWarning: "is" with a literal. Did you mean "=="?
return to_validate is "valid"
```
=> Fix an errant string identity comparison in a test

poetry.lock, tests/integration/validation/test_exceptions.py
[openapi-schema-validator 0.4.2](https://github.com/p1c2u/openapi-schema-validator/releases/tag/0.4.2) fixed the following  issue:
* Missing format checker for format no longer raise `FormatError`
This means it will no longer raise spec `OpenAPIValidationError` error
Fixes #189
=> fix custom format checker not found test

openapi_spec_validator/validation/validators.py, tests/integration/data/v3.0/property-missing-reference.yaml, tests/integration/validation/test_validators.py
=> property missing reference fix

openapi_spec_validator/validation/validators.py, poetry.lock, pyproject.toml, tests/integration/test_shortcuts.py, tests/integration/validation/test_validators.py
Support for jsonschema 4.18.x and jsonschema-spec 0.2.x
Fixes #201
=> jsonschema 4.18 compatibility

openapi_spec_validator/__main__.py
=> Allow validate multiple files

poetry.lock, tests/integration/data/v3.0/read-only-write-only.yaml, tests/integration/validation/test_validators.py
Fixes #253
openapi-schema-validator 0.6.2 version updated
=> Read-only write-only spec test

docs/python.rst, openapi_spec_validator/__init__.py, openapi_spec_validator/__main__.py, openapi_spec_validator/exceptions.py, openapi_spec_validator/schemas/__init__.py, openapi_spec_validator/shortcuts.py, openapi_spec_validator/validation/__init__.py, openapi_spec_validator/validation/caches.py, openapi_spec_validator/validation/decorators.py, openapi_spec_validator/validation/finders.py, openapi_spec_validator/validation/keywords.py, openapi_spec_validator/validation/proxies.py, openapi_spec_validator/validation/registries.py, openapi_spec_validator/validation/types.py, openapi_spec_validator/validation/validators.py, tests/integration/conftest.py, tests/integration/test_main.py, tests/integration/test_shortcuts.py, tests/integration/validation/test_exceptions.py, tests/integration/validation/test_validators.py
`openapi_*_spec_validator` objects are deprecated. Use `*SpecValidator` classes instead.
=> Validators refactor

README.rst, docs/python.rst, openapi_spec_validator/__init__.py, openapi_spec_validator/__main__.py, openapi_spec_validator/shortcuts.py, openapi_spec_validator/validation/validators.py, tests/integration/test_shortcuts.py, tests/integration/validation/test_validators.py
Deprecates `validate_spec` and `validate_spec_url`
=> validate and validate_url shortcuts

openapi_spec_validator/validation/keywords.py, tests/integration/validation/test_exceptions.py
According to the OpenAPI spec this is allowed. This should solve #97
=> Allow undefined required properties

.readthedocs.yaml
Read the Docs builds began permanently failing on February 26, 2024.
The differential diagnosis between success and failure seems to be that [the last successful build](https://app.readthedocs.org/projects/openapi-spec-validator/builds/23513651/#220526594--2) used Poetry 1.7.1; [the first failing build](https://app.readthedocs.org/projects/openapi-spec-validator/builds/23567051/#221127792--2) used Poetry 1.8.1. For reference, Poetry 1.8.1 was released on February 26, 2024.
Read the Docs later updated its ["Install dependencies with Poetry" documentation](https://docs.readthedocs.com/platform/stable/build-customization.html#install-dependencies-with-poetry) to note that Poetry needs a `$VIRTUAL_ENV` environment variable set.
This change aligns the Read the Docs config with the documented …
=> Fix Read the Docs builds

hooks.yaml
pre-commit doesn't use `hooks.yaml` [[docs link](https://pre-commit.com/#creating-new-hooks)] -- it relies on `.pre-commit-hooks.yaml`.
Therefore this PR removes the unused `hooks.yaml` file.
=> Remove `hooks.yaml`, which is unused by pre-commit
