- openapi_spec_validator/decorators.py
- tests/integration/data/v3.0/parent-reference/common.yaml
- tests/integration/data/v3.0/parent-reference/openapi.yaml
- tests/integration/data/v3.0/parent-reference/spec/components.yaml
- tests/integration/data/v3.0/petstore-separate/spec/schemas/Pets.yaml
- tests/integration/test_validate.py
Fixes https://github.com/p1c2u/openapi-spec-validator/issues/7
reference scopes stacks issue
> Reference scopes stack fix

- .travis.yml
- openapi_spec_validator/resources/schemas/v2.0/schema.json
- setup.py
- tox.ini
> use local copy of swagger2 schema

- openapi_spec_validator/constructors.py
- openapi_spec_validator/handlers.py
- openapi_spec_validator/loaders.py
- openapi_spec_validator/schemas.py
- tests/integration/conftest.py
- tests/integration/data/v2.0/petstore.yaml
- tests/integration/data/v3.0/petstore.yaml
This PR relates to #29 
Introduces extended yaml safe loader which converts integer keys to strings 
Fixes #26
> Allow integer response code

- requirements.txt
- setup.py
> pyaml dependecy drop off

- openapi_spec_validator/validators.py
- tests/integration/test_validators.py
> Validate default values

- requirements.txt
- setup.py
Security update 
https://nvd.nist.gov/vuln/detail/CVE-2017-18342
> Requirements update

- openapi_spec_validator/__main__.py
- setup.py
In order to allow Windows user to use this smart tool, this PR provide a
solution proposed by @kearnh in Issuer #50.
> :bug: Fixing URI forge for Windows

- .pre-commit-hooks.yaml
- hooks.yaml
- setup.py
Adds support for [pre-commit](https://pre-commit.com/).
Would need this commit to be tagged too if possible so pre-commit can pick it up!
> Adds support for pre-commit

- NOTICE
- README.md
> License NOTICE

- README.rst
- openapi_spec_validator/__main__.py
- openapi_spec_validator/readers.py
> Readers and README update

- openapi_spec_validator/validators.py
- requirements.txt
- setup.cfg
- tests/integration/test_validators.py
> Repair default and $ref issue

- openapi_spec_validator/__init__.py
- openapi_spec_validator/resources/schemas/v3.0/schema.json
- tests/integration/test_validators.py
Based on latest 3.0.x schema
https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/
> Spec 3.0 schema

- .github/workflows/docker-publish.yml
> Docker publish github action

- .github/workflows/python-test.yml
- openapi_spec_validator/handlers/file.py
- openapi_spec_validator/handlers/utils.py
> File handler Windows compatibility fix

- .github/workflows/python-test.yml
- poetry.lock
- pyproject.toml
Hello, thanks for this tool!
This adds a dependency on `setuptools` to appease ` import pkg_resources` and sorts the dependencies.
Feel free to close this and fix it properly, if i did it wrong! I don't do a lot of poetry work, so assume that something would have to happen to update the lockfile...
> add setuptools dependency for pkg_resources, sort deps

- tests/integration/validation/test_exceptions.py
> custom format tests

- poetry.lock
- pyproject.toml
Relates to https://github.com/p1c2u/openapi-core/issues/456
> allow openapi-schema-validator 0.4

- openapi_spec_validator/schemas/utils.py
- openapi_spec_validator/validation/validators.py
- tests/integration/data/v3.0/property-recursive.yaml
- tests/integration/validation/test_exceptions.py
- tests/integration/validation/test_validators.py
> schema properties validation recursion fix

- poetry.lock
- pyproject.toml
> update openapi-schema-validator dependecy

- openapi_spec_validator/resources/schemas/v3.1/schema.json
> Fix typo in server variables schema for OpenAPI 3.1.0

- openapi_spec_validator/resources/schemas/v3.1/schema.json
- tests/integration/data/v3.1/petstore.yaml
> allow path item ref fix

- .github/workflows/python-test.yml
- .travis.yml
- docs/conf.py
- openapi_spec_validator/validation/protocols.py
- poetry.lock
- pyproject.toml
> drop python 3.7 support
